# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class TextToSpeechStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.speak = channel.unary_unary(
        '/TextToSpeech/speak',
        request_serializer=service__pb2.Text.SerializeToString,
        response_deserializer=service__pb2.TTSResponse.FromString,
        )


class TextToSpeechServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def speak(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TextToSpeechServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'speak': grpc.unary_unary_rpc_method_handler(
          servicer.speak,
          request_deserializer=service__pb2.Text.FromString,
          response_serializer=service__pb2.TTSResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TextToSpeech', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
